### PR TITLE
MAINT: move last plots from Environment class

### PR DESCRIPTION
**Pull request by Gui-FernandesBR**
## Pull request type

Please check the type of change your PR introduces:

- [x] Code maintenance (refactoring, formatting, renaming, tests)

## Pull request checklist

Please check if your PR fulfills the following requirements, depending on the type of PR:

- Code base maintenance (refactoring, formatting, renaming):

  - [x] Docs have been reviewed and added / updated if needed
  - [x] Lint (`black rocketpy`) has passed locally and any fixes were made
  - [x] All tests (`pytest --runslow`) have passed locally

## What is the new behavior?

The very same behavior, the very same results, but now there is no `plt.plot(...` inside the Enrivonment class

## Does this introduce a breaking change?

- [x] No

## Other information

This PR could be seen as an extension of #296

### CODE REVIEW

**Comment by Gui-FernandesBR** [comment]
Ready for review ✅👌

**Review by MateusStano — CHANGES_REQUESTED** [review]
Everything seems good! Just one thing:

image

The lines are above the legend. Maybe this can be fixed using the `zorder` param of matplotlib?

**Comment by MateusStano** [comment]
> What I think is weird is that only the speed of sound have label/lengend. Any reason to that?

Yeah, that is weird. Couldn't figure out how to fix it but found two things:

1. The name of the axes labels are wrong
2. And more importantly, those plots don't need legend because the different axes are already displayed in different colors !!

I think just removing the legend here will work

**Comment by Gui-FernandesBR** [comment]
Ready for a re-review @MateusStano

**Review by MateusStano — APPROVED** [review]

**Pull request merged**
