### PR TITLE
MAINT: Cleaning up some repo files

### PR DESCRIPTION
**Pull request by Gui-FernandesBR**
## Pull request type

Please check the type of change your PR introduces:
- [x] GitHub maintenance

## Pull request checklist

Please check if your PR fulfills the following requirements, depending on the type of PR:

- ReadMe, Docs and GitHub maintenance:

  - [x] Spelling has been verified
  - [x] Code docs are working correctly 

## What is the current behavior?

When trying to download (i.e. to clone) the RocketPy repository, usually the user also downloads several files that he/she will probably not use. Some of the files were added in the first upload of this repo and have never been used since then.

## What is the new behavior?

38 data files are being deleted from this repo. I'm saving them in our organizational gdrive account, so we never lost it.
Cloning the repo should be easier now.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Gui-FernandesBR** [comment]
This is part 1 of issue #281

**Comment by Gui-FernandesBR** [comment]
Kinda bothers me how the thrust file for the keron motor is repeated 3 times in the repo (1 for tests,1 for data/motors, and 1 for dispersion analysis), even if it is a small file, it is annoying.
Accepting suggestions if they are easy to implement, otherwise let's just move forward.

**Comment by MateusStano** [comment]
> Kinda bothers me how the thrust file for the keron motor is repeated 3 times in the repo (1 for tests,1 for data/motors, and 1 for dispersion analysis), even if it is a small file, it is annoying. Accepting suggestions if they are easy to implement, otherwise let's just move forward.

I think it would be better if every data files were only found inside the data folder and everything has to access to them from there. 

For the tests to work are the data files required to be inside the tests folder? If so then I would suggest that we leave the keron file inside the tests folder, which is better than repeating the file more than once.

If the tests don't require the files to be inside the tests folder then I think is better to create a standard and leave all data-related files inside the data folder and remove them from the fixtures folder

**Review by MateusStano — APPROVED** [review]

**Comment by Gui-FernandesBR** [comment]
> For the tests to work are the data files required to be inside the tests folder? 

Not, it is not. Indeed, some of the tests already uses the files available at data folder.
I agree on moving data from tests to data folder. Let's see what @giovaniceotto think about it, since he was the one who created the fixtures.

Also, I think that the data folder should contain only raw data files, I mean, mainly .csv or .json file.
Any code (.py or .ipnb) should be at examples or docs.

**Comment by giovaniceotto** [comment]
Sorry guys... Was this branch merged into master without any tests passing?

**Comment by Gui-FernandesBR** [comment]
> Sorry guys... Was this branch merged into master without any tests passing?
> 
> 

If I understood correctly, the problem with tests were related to the timezonefinder issue.
Codes were running locally.
None of the deleted files were being used by tests of notebooks.
None of the tests or codes were modified.

Nevertheless, I restored the branch if you want to further investigate.

**Pull request merged**
