### PR TITLE
FIX: Broken Function.get_value_opt for N-Dimensional Functions

### PR DESCRIPTION
**Pull request by giovaniceotto**
## Pull request type

- [x] Code changes (bugfix, features)

## Checklist

- [x] Tests for the changes have been added (if needed)
- [x] Docs have been reviewed and added / updated
- [x] Lint (`black rocketpy/ tests/`) has passed locally 
- [x] All tests (`pytest --runslow`) have passed locally
- [ ] `CHANGELOG.md` has been updated (if relevant)

## Current behavior

As reported by @styris00, the following code shows an error with `Function.get_value_opt` when used with 2D functions.

```
import numpy as np
from rocketpy import Function

arr = np.array([(1, 1, 2), (3, 6, 8),
            (8, 8, 9)])

myFun = Function(
    arr,
    interpolation="shepard",
    extrapolation="natural",
    title="myFun"
)

myFun.set_get_value_opt()

print(myFun.get_value(1, 1)
print(myFun.get_value_opt(1, 1))
```

Output is:

```
2.0
1.0
```

## New behavior

The bug was fixed.

## Breaking change

- [x] No

### CODE REVIEW

**Comment by Gui-FernandesBR** [comment]
I wonder when this bug was introduced. The tests haven't been modified recently.

**Review by Gui-FernandesBR — DISMISSED** [review]

**Review by styris00 — APPROVED** [review]

**Comment by giovaniceotto** [comment]
> I wonder when this bug was introduced. The tests haven't been modified recently.

I didn't have enough time to track it down (the snake case commit makes things harder). However, the old test was never going to catch the bug.

What was going on is that, considering x, y, z, `get_value_opt` was returning y instead of z.  And, in the test, y was equal to z, so it passed.

**Comment by giovaniceotto** [comment]
Are we going to make this into a hotfix?
@MateusStano

**Comment by MateusStano** [comment]
> Are we going to make this into a hotfix?
> @MateusStano

Yes we are!

**Review by MateusStano — APPROVED** [review]

**Review by Gui-FernandesBR — APPROVED** [review]

**Pull request merged**
