### PR TITLE
MAINT: auto assign workflows

### PR DESCRIPTION
**Pull request by Gui-FernandesBR**
## Pull request type

Please check the type of change your PR introduces:

- [X] ReadMe, Docs and GitHub maintenance

## Pull request checklist

Please check if your PR fulfills the following requirements, depending on the type of PR:

- ReadMe, Docs and GitHub maintenance:

  - [X] Spelling has been verified
  - [X] Code docs are working correctly 

## What is the new behavior?

I'm trying to add the following workflows to this setup
- Auto asign issue or pull request once they are created, by using the author as assignee
- Automaticallyy add issues am PR to github project once they are opened (this may need testing a little bit more before merging

## Does this introduce a breaking change?

- [X] No

### CODE REVIEW

**Comment by giovaniceotto** [comment]
Great idea! Have you been able to test if these actions work?

**Comment by Gui-FernandesBR** [comment]
> Great idea! Have you been able to test if these actions work?

I've tested the auto-assingment for issues and pull requests and worked correctly. It assigns the author as assignee (for issues we could re-think that) and the reviewers of PRs are automatically me, giovani and Stano.

For the projects assignment I was not able to test in another public repository. Had some in a private one earlier, but the worst case scenario is that that workflow doesn't work and therefore the issue/task is not added to the project. So in the end of the day would not be bad if it doesn't work on our first try.

Anyway, once we discuss every detail, would you like to merge this before or after the 2022 hackathon? Take in mind that this will assign 3 people as reviewers for every PR, for instance. But of course we could modify the workflow to work properly during hackathon, we could do this in another fork

**Comment by Gui-FernandesBR** [comment]
Expected behavior:
image

**Comment by Gui-FernandesBR** [comment]
@giovaniceotto @MateusStano @PatrickSampaioUSP , I'm asking review from one of you.

Can we proceed with approving/merging?

Everything should be working now.

**Comment by giovaniceotto** [comment]
@PatrickSampaioUSP is better suited to review this one. I'll add him as soon as he accepts the invite to participate in this repo.

**Comment by giovaniceotto** [comment]
Added @PatrickSampaioUSP as a reviewer.

**Review by PatrickSampaioUSP — APPROVED** [review]
Sounds good, we should merge it and test

**Comment by Gui-FernandesBR** [comment]
Idk why but this not worked when Franz opened the last PR

**Comment by giovaniceotto** [comment]
Still not working, right?

**Pull request merged**
