### PR TITLE
ENH: Parachute.info() method created

### PR DESCRIPTION
**Pull request by Gui-FernandesBR**
## Pull request type

Please check the type of change your PR introduces:

- [x] Code maintenance (refactoring, formatting, renaming, tests)

## Pull request checklist

Please check if your PR fulfills the following requirements, depending on the type of PR:

- Code base maintenance (refactoring, formatting, renaming):

  - [x] Docs have been reviewed and added / updated if needed
  - [x] Lint (`black rocketpy`) has passed locally and any fixes were made
  - [x] All tests (`pytest --runslow`) have passed locally

## What is the current behavior?

It is hard to plot and print information regarding the parachutes.

## What is the new behavior?

Parachute class now presents more options to make or life easier when plotting everything.

## Does this introduce a breaking change?

- [x] No

### CODE REVIEW

**Comment by Gui-FernandesBR** [comment]
#312

**Comment by giovaniceotto** [comment]
@Gui-FernandesBR, can you fill out the PR description to better explain this PR?

I would specially like a description of the new class architecture with this new print method. Furthermore, was this framework inspired by some other work?

**Comment by Gui-FernandesBR** [comment]
> @Gui-FernandesBR, can you fill out the PR description to better explain this PR?
> 
> I would specially like a description of the new class architecture with this new print method. Furthermore, was this framework inspired by some other work?

It's filled now. I recommend starting by the #326 .

It is inspired in the #287 , see its thread for more details.

**Review by MateusStano — APPROVED** [review]
Great! Really like the `__str__` method.

**Pull request merged**
