### PR TITLE
DOC: Faraday 2023 flight sim

### PR DESCRIPTION
**Pull request by LUCKIN13**
## Pull request type

- [ ] Code changes (bugfix, features)
- [ ] Code maintenance (refactoring, formatting, tests)
- [x] ReadMe, Docs and GitHub updates

## Checklist

- [x] Docs have been reviewed and added / updated
- [x] Lint (`black rocketpy/ tests/`) has passed locally 
- [x] All tests (`pytest tests -m slow --runslow`) have passed locally
- [ ] `CHANGELOG.md` has been updated (if relevant)

## Additional information
 This branch still needs some data reviews since the simulation file was developed in an older version of RocketPy. However, reviews can already be made, since the example should only suffer minor changes, if needed. 
Changelog and  Index for examples will be updated in other flight example, to prevent conflicts.

### CODE REVIEW

**Review by Gui-FernandesBR — CHANGES_REQUESTED** [review]
Really nice addition. I have a few comments to share:

1. Can you check with the team (maybe reading their technical report) if you could improve the drag curves at least by adding a few more points? Even openrocket drag curve would already be beneficial to us. A constant value is not really helping here.
image

2. Also, the altitude of ejection of the main parachute seems to not be right. Any chance this value was different?
3. Please add the new flight to the `https://docs.rocketpy.org/en/latest/examples/index.html` page.
4. As Faraday is a team and not a rocket, I'm afraid we should change the name of the folder you have created. Probably this will not be the last rocket from faraday that we add to our docs.

**Comment by LUCKIN13** [comment]
Thanks Gui for your review. Valid points, almost totally fixed. 
In terms of the drag data, that's the only data we have. I'll try contacting the team, to see if we can improve that example!

**Comment by Gui-FernandesBR** [comment]
> Thanks @Gui-FernandesBR for your review. Valid points, almost totally fixed. In terms of the drag data, that's the only data we have. I'll try contacting the team, to see if we can improve that example!

Understood.

I noticed the power_on drag is higher than the power_off drag. It should be the opposite tho.
If you swap those files, does the results get better or worse? If worse, just forget about what I said.

**Comment by LUCKIN13** [comment]
@Gui-FernandesBR just went with the higher value in drag. 30 meters reduction, and I believe that since is a constant drag, it's difficult to reach better results. This can be updated later, if the team gives us more data.

**Comment by Gui-FernandesBR** [comment]
> @Gui-FernandesBR just went with the higher value in drag. 30 meters reduction, and I believe that since is a constant drag, it's difficult to reach better results. This can be updated later, if the team gives us more data.

Great work. That's what I expected.
5% is already really nice.

Off-topic, I believe GitHub has solved a long-known-issue which is the notebook diffs.

image

**Review by Gui-FernandesBR — APPROVED** [review]
LGTM, another amazing example added to our docs! 

@LUCKIN13 go ahead and merge this PR.
I recommend using the **Squash and merge** option since the PR had several adjustment commits.
You have done an amazing job here.

**Pull request merged**
