### PR TITLE
ENH: Adding .nc files for EnvAnalysis at EuroC

### PR DESCRIPTION
**Pull request by Gui-FernandesBR**
## Pull request type

Please check the type of change your PR introduces:
- [ ] Other: Files addition

## Pull request checklist

Please check if your PR fulfills the following requirements, depending on the type of PR:

- ReadMe, Docs and GitHub maintenance:

  - [ ] Spelling has been verified
  - [ ] Code docs are working correctly 

- Code base maintenance (refactoring, formatting, renaming):

  - [ ] Docs have been reviewed and added / updated if needed
  - [ ] Lint (`black rocketpy`) has passed locally and any fixes were made
  - [ ] All tests (`pytest --runslow`) have passed locally

- Code base additions (for bug fixes / features):

  - [ ] Tests for the changes have been added
  - [ ] Docs have been reviewed and added / updated if needed
  - [ ] Lint (`black rocketpy`) has passed locally and any fixes were made
  - [ ] All tests (`pytest --runslow`) have passed locally

## What is the new behavior?

Two new files, on for surfaceData and other for pressureLevelData

## Does this introduce a breaking change?
- [ ] Yes
- [X] No

## Other information
Just openning this PR to ensure files are working properly before merging the commits!

### CODE REVIEW

**Comment by Gui-FernandesBR** [comment]
Currently files does generate proper simulations, check the following results:

> Gravity Details
> 
> Acceleration of Gravity: 9.80665 m/s²
> 
> 
> Launch Site Details
> 
> Launch Rail Length: 5  m
> Launch Date: 2007-10-15 12:00:00 UTC
> Launch Site Latitude: 39.25000°
> Launch Site Longitude: -8.00000°
> Launch Site Surface Elevation: 0.0 m
> 
> 
> Atmospheric Model Details
> 
> Atmospheric Model Type: Reanalysis
> Reanalysis Maximum Height: 31.048 km
> Reanalysis Time Period: From  2002-10-09 00:00:00  to  2010-10-20 23:00:00  UTC
> Reanalysis Hour Interval: 3  hrs
> Reanalysis Latitude Range: From  39.5 ° To  39.0 °
> Reanalysis Longitude Range: From  -8.25 ° To  -7.75 °
> 
> 
> Surface Atmospheric Conditions
> 
> Surface Wind Speed: 1.20 m/s
> Surface Wind Direction: 112.54°
> Surface Wind Heading: 292.54°
> Surface Pressure: 1000.00 hPa
> Surface Temperature: 295.28 K
> Surface Air Density: 1.180 kg/m³
> Surface Speed of Sound: 344.48 m/s 

image

**Comment by Gui-FernandesBR** [comment]
And tests from github action will start to work only once #237 is merged into both enh/env_analysis_euroc and env_analysis_euroc_add_files

**Comment by giovaniceotto** [comment]
I know this is holding back development, so I will approve it and let you merge if you need it.

However, I find the file sizes strange. The pressure level file is only 4 MB while the surface level data is 40 MB. For SACup files, the exact opposite occurs. Why is this the case?

Furthermore, "Reanalysis Time Period: From 2002-10-09 00:00:00 to 2010-10-20 23:00:00 UTC" seems wrong as well. Shouldn't the files cover until 2021?

**Review by giovaniceotto — APPROVED** [review]

**Review by giovaniceotto — APPROVED** [review]

**Comment by Gui-FernandesBR** [comment]
Note to selff: Need to check the maximum range of some years in the file

**Pull request merged**
