### PR TITLE
DOC: fix Getting Started notebooks Dynamic Analysis section

### PR DESCRIPTION
**Pull request by giovaniceotto**
## Pull request type

Please check the type of change your PR introduces:

- [x] ReadMe, Docs and GitHub maintenance

## Pull request checklist

Please check if your PR fulfills the following requirements, depending on the type of PR:

- ReadMe, Docs and GitHub maintenance:

  - [x] Spelling has been verified
  - [x] Code docs are working correctly 

## What is the current behavior?

As reported in #292, the Dynamic Stability Analysis section of the Getting Started Notebook is not working as expected:

image

## What is the new behavior?

The problem was that the variable `factor` was not being used inside the for loop. This has been fixed:

image

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Should be merged directly into master since it is not related to the core code, but to the documentation. Once merged, the documentation will be updated automatically.

### CODE REVIEW

**Comment by giovaniceotto** [comment]
@Gui-FernandesBR, please consider the importance of us merging this PR fast since the latest documentation is wrong.

**Comment by Gui-FernandesBR** [comment]
Shall we use %matplotlib inline instead of widget? This way the plots are rendered in docs section, wllowing us to see what is being shown to be readers

**Review by Gui-FernandesBR — APPROVED** [review]
Ty, awesome update

**Comment by Gui-FernandesBR** [comment]
@giovaniceotto ,

https://docs.rocketpy.org/en/latest/notebooks/getting_started.html

It is still using `%matplotlib widget` here, therefore all the plots are not rendered.
The code is correct though. And running at colab worked too.

**Pull request merged**
