### PR TITLE
DOC: RED Flight Example 

### PR DESCRIPTION
**Pull request by LUCKIN13**
## Pull request type

- [ ] Code changes (bugfix, features)
- [ ] Code maintenance (refactoring, formatting, tests)
- [x] ReadMe, Docs and GitHub updates

## Checklist

- [x] Docs have been reviewed and added / updated
- [x] Lint (`black rocketpy/ tests/`) has passed locally 
- [x] All tests (`pytest tests -m slow --runslow`) have passed locally
- [ ] `CHANGELOG.md` has been updated (if relevant)

## Additional information
 This branch still needs some data reviews since the simulation file was developed in an older version of RocketPy. However, reviews can already be made, since the example should only suffer minor changes, if needed. 
Changelog and  Index for examples will be updated in other flight example, to prevent conflicts.

### CODE REVIEW

**Review by Gui-FernandesBR — CHANGES_REQUESTED** [review]
Once again, naming the folder after the team name is risky, since this may not be the last rocket we use as an example from this team.

The apogee should be quite near 3000m, since the rocket has an airbrake model. Are you sure the air brakes have worked during this simulation? 8.6% of accuracy is too much, I was expecting something below 2% for this model (of course I could be wrong about this.

I personally recommend you to not mention the "last simulated apogee before launch", instead just mention the simulation we have obtained right now.

Plus, we need to add this new rocket to the flight examples comparison plot.

**Comment by Gui-FernandesBR** [comment]
@LUCKIN13 before merging this PR, I believe we should add it to the CHANGELOG file.
#732 is similar.

**Comment by LUCKIN13** [comment]
> The apogee should be quite near 3000m, since the rocket has an airbrake model. Are you sure the air brakes have worked during this simulation? 8.6% of accuracy is too much, I was expecting something below 2% for this model (of course I could be wrong about this.

The airbrakes did work, since the apogee was 3300 meters and is now 3180m. I have an idea for an improvement to that value, based on using the actuation curve of the controller designed by the team.

**Review by Gui-FernandesBR — COMMENTED** [review]
@LUCKIN13 it looks like you have duplicated the example notebook.

image

**Comment by LUCKIN13** [comment]
@Gui-FernandesBR thanks for calling out my distraction! I think it's finally ready!

**Review by Gui-FernandesBR — APPROVED** [review]
LGTM

**Pull request merged**
