### PR TITLE
FIX: funcify titles - pt1

### PR DESCRIPTION
**Pull request by phmbressan**
## Pull request type

Please check the type of change your PR introduces:

- [X] Code base additions (bugfix, features)
- [ ] Code maintenance (refactoring, formatting, renaming, tests)
- [ ] ReadMe, Docs and GitHub maintenance
- [ ] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements, depending on the type of PR:

- Code base additions (for bug fixes / features):

  - [ ] Tests for the changes have been added
  - [ ] Docs have been reviewed and added / updated if needed
  - [X] Lint (`black rocketpy`) has passed locally and any fixes were made
  - [X] All tests (`pytest --runslow`) have passed locally

## What is the current behavior?

The `funcify_method` decorator from `Function` did not update the titles for methods that returned `Function` instances.

## What is the new behavior?

This issue was fixed by updating the `reset` method from `Function` with a call to `setTitle`.

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by MateusStano** [comment]
I do not think this is fixing the issue.

Running `getting_started.ipynb` I still get the same results as before:

image


image

**Comment by phmbressan** [comment]
> I do not think this is fixing the issue.
> 
> Running `getting_started.ipynb` I still get the same results as before:
> 

Thank you for pointing it out. This is odd since I have run some motor notebooks to test it and they seemed normal. Perhaps there is an specific method in getting started that is triggering it. I will check it ASAP.

**Comment by phmbressan** [comment]
I understand it now. The issue here is that the `beta V.1` branch does not implement `funcify` on the `Motors` methods. Therefore the Function titles will be propagated through many calculations leading to the result above. 

My understanding of the problem was too shallow, I am sorry about that, I tought that it only happened due to `funcify`. I will fix it.

**Comment by Gui-FernandesBR** [comment]
> I understand it now. The issue here is that the `beta V.1` branch does not implement `funcify` on the `Motors` methods. Therefore the Function titles will be propagated through many calculations leading to the result above.
> 
> My understanding of the problem was too shallow, I am sorry about that, I tought that it only happened due to `funcify`. I will fix it.

Don't worry. At least you tried.
Please ask for review again when it is ready, I converted the PR to draft.

There's no problem if we leave this one out of our pre-release

**Review by Gui-FernandesBR — APPROVED** [review]
Works on my machine 🧑‍💻

Partial solution only, tho.

Hope to see you solving the bigger issue regarding Function operations titles later :)

**Pull request merged**
