### PR TITLE
DOC : Halcyon Flight Example

### PR DESCRIPTION
**Pull request by LUCKIN13**
## Pull request type

- [x] ReadMe, Docs and GitHub updates

## Checklist

- [x] Tests for the changes have been added (if needed)
- [x] Docs have been reviewed and added / updated
- [ ] Lint (`black rocketpy/ tests/`) has passed locally 
- [x] All tests (`pytest tests -m slow --runslow`) have passed locally
- [ ] `CHANGELOG.md` has been updated (if relevant)

## Description
 Added files for Halcyon flight example from Aerospace Team Graz. 

## Additional Information

Seems like the data for the atmospheric model is not equal to the registered in the flight simulation before the launch.

### CODE REVIEW

**Comment by Gui-FernandesBR** [comment]
Great work, @LUCKIN13 !!

I've upload the `.nc` file that will allow us to simulate all the flights for the EuRoC 2023. I think it is better to use these data rather than relying on Windy. I downloaded the data from Copernicus (ECMWF) server earlier this year, and it is the same file used to create the EuRoC 2023 post-flight report.

**Comment by Gui-FernandesBR** [comment]
I think in this case it is worth it to add the second plot as well. Can you give it a try, @LUCKIN13 ? Now you should be able to make the GNSS data comparison using the .nc file

image

**Comment by LUCKIN13** [comment]
Thanks for your input, Already added the latitude and longitude plots and they look great when compared to the reality. However, the descent phase of the flight seems to happen quicker. 
I triple checked all the parameters and it's all equal to the ones used in the last simulation.

**Review by Gui-FernandesBR — APPROVED** [review]
Great addition to our example gallery!

**Pull request merged**
