### PR TITLE
BUG: Allow multiple sets of stochastic fins

### PR DESCRIPTION
**Pull request by WilliamArmst**
## Pull request type

Bugfix

## Checklist

- [x] Lint (`black rocketpy/ tests/`) has passed locally 
- [x] All tests (`pytest tests -m slow --runslow`) have passed locally
- [x] `CHANGELOG.md` has been updated (if relevant)

## Current behavior

If there is a rocket with 2 sets of fins and you try to make them stochastic, the function that is fixed in the code will throw because it only checks the first set of fins.  This makes it impossible to add 2 sets of fins.

Here is a sample program if you wish to confirm:
```py
from rocketpy import TrapezoidalFins, Rocket, StochasticTrapezoidalFins, StochasticRocket

# apply percent standard deviation to components
percentStdDeviation = 0.1

testRocket = Rocket( # All of the data is incorrect
    radius=0.1,
    mass=1,
    inertia=(6.321, 6.321, 0.034),
    power_off_drag= "powerOffDragCurve.csv",
    power_on_drag= "powerOnDragCurve.csv",
    center_of_mass_without_motor=0.5,
    coordinate_system_orientation="tail_to_nose",
)
fin_set_1 = testRocket.add_trapezoidal_fins(
    n=4,
    root_chord=0.203,
    tip_chord=0.0381,
    span=0.102,
    sweep_length=0.21,
    position=-0.015,
    cant_angle=0.5,
    airfoil=("airfoil_example.csv","radians"), # insert a .csv file for the side profile of the fin
)
fin_set_2 = testRocket.add_trapezoidal_fins(
    n = 4,
    root_chord=0.203,
    tip_chord=0.0381,
    span=0.102,
    sweep_length=0.21,
    position=-1.945,
    cant_angle=0.5,
    airfoil=("airfoil_example.csv","radians"), # insert a .csv file for the side profile of the fin
)
fin_set_3 = TrapezoidalFins(
    n = 4,
    root_chord=0.203,
    tip_chord=0.0381,
    span=0.102,
    sweep_length=0.21,
    cant_angle=0.5,
    rocket_radius=0.1,
    airfoil=("airfoil_example.csv","radians"), # insert a .csv file for the side profile of the fin
)

stochastic_fin_set_1_object = StochasticTrapezoidalFins(
    trapezoidal_fins=fin_set_1,
    root_chord=percentStdDeviation * fin_set_1.root_chord,
    tip_chord=percentStdDeviation * fin_set_1.tip_chord,
    span=percentStdDeviation * fin_set_1.span,
    sweep_length=percentStdDeviation * fin_set_1.sweep_length,
    cant_angle=0.01, # +- 0.01deg
)
stochastic_fin_set_2_object = StochasticTrapezoidalFins(
    trapezoidal_fins=fin_set_2,
    root_chord=percentStdDeviation * fin_set_2.root_chord,
    tip_chord=percentStdDeviation * fin_set_2.tip_chord,
    span=percentStdDeviation * fin_set_2.span,
    sweep_length=percentStdDeviation * fin_set_2.sweep_length,
    cant_angle=0.01, # +- 0.01deg
)

stochastic_testRocket = StochasticRocket(
    rocket=testRocket,
    radius=0.1 * testRocket.radius,
    mass=0.1 * testRocket.mass,
    center_of_mass_without_motor=0.1 * testRocket.center_of_mass_without_motor,
)

stochastic_fin_set_sustainer_Event1 = stochastic_testRocket.add_trapezoidal_fins(
   fins=stochastic_fin_set_1_object,
   position=0.01, # +-1cm
)

stochastic_fin_set_booster_Event1 = stochastic_testRocket.add_trapezoidal_fins(
    fins=stochastic_fin_set_2_object,
    position=0.01, # +-1cm
)

testRocket.draw()
```

I also tested adding a stochastic fin that actually wasn't a part of the rocket, and it still catches that error (replace one of the ``trapezoidal_fins=`` with ``fin_set_3`` to see this work)

## New behavior

Behaves as expected.

## Breaking change

- [ ] Yes
- [x] No

## Additional information

I thought I figured out the git stuff but ig I didn't.  Oh well.  I am allowed to not know how to use git because I am fixing your bugs.

### CODE REVIEW

**Comment by Gui-FernandesBR** [comment]
@WilliamArmst regarding git, we are working on an improvement to our development documentation, I think that should help you to understand what is happening.

This is what I recommend you to do:

```bash
git checkout origin develop
git pull
git checkout -   # this goes to your previous branch
git rebase -i develop  # this will rebase your branch on top of develop, allowing you to decide what to do with each commit
```

This will open an editor, which could be vim or nano, for example.
Delete all the lines that contains commits you do not want to include in this PR. Simply let the last 2 commits, you can keep the "pick" option by the begining of each line.
Save the operation and see the 

```bash
git log --graph --oneline
```

You should expect something like this:
image


If everything is correct, try to push again:

```bash
git push
```

or, as I like to do:

```bash
git push -f
```

**Comment by WilliamArmst** [comment]
Ok so I did not do it right.

**Comment by Gui-FernandesBR** [comment]
> Ok so I did not do it right.

Don't worry, we can get you from here. Not a problem.

Dealing with rebase isn't  so trivial.

Next branch you open, try to git pull before creating the new branch, that might help you.

If you plan to open more PRs, please let me know so I grant you permission to create branches directly in our repos instead of your fork, that could make your life easier.

**Comment by WilliamArmst** [comment]
I think I got it

**Comment by WilliamArmst** [comment]
I think it might be because I only forked the master branch, but I now have the develop one too.  I should be all good going forward.

**Review by Gui-FernandesBR — APPROVED** [review]
Tests are passing locally, including slow tests.

This time I won't wait for regression tests, let's keep moving.

Thx again for another problem solved, @WilliamArmst !

**Pull request merged**
